### PR TITLE
SIG meeting time and frequency

### LINKED ISSUE #31: SIG meeting time and frequency
The weekly security sig meeting is usually fairly quiet as far as attendance. I worry that we may not always have people that can take action in the discussion. Should the meeting time be changed? Is the frequency a problem?

### PR DESCRIPTION
**Pull request by jpkrohling**
Fixes #31

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Can the cadence be changed to biweekly as well? It's very rarely attended, making it less frequent may improve attendance

**Comment by jpkrohling** [comment]
Indeed! I changed it. Note that I also added you to the leadership, as you are part of @open-telemetry/sig-security-maintainers

**Comment by jpkrohling** [comment]
@codeboten, if this looks OK, can you review/merge? I'll change the schedule as soon as this is merged.

**Review by cpanato — APPROVED** [review]
lgtm +1

**Review by codeboten — COMMENTED** [review]
Thanks @jpkrohling, note that the change in schedule will make it very unlikely (5am here) for me to attend, any chance to move this up by 2 hours to 14:00 UTC?

**Review by codeboten — APPROVED** [review]
🎉

**Pull request merged**
