### PR TITLE
Issues contributor

### PR DESCRIPTION
**Pull request by oly-baby**
Added a recomendation that security SIG should be to always bind to localhost rather than to 0.0.0.0 or any interface.

### CODE REVIEW

**Review by codeboten — CHANGES_REQUESTED** [review]
Please add the contents of this doc to https://github.com/open-telemetry/sig-security/blob/main/docs/recommendations.md

**Review by oly-baby — COMMENTED** [review]
Adding recommendation around binding to network interfaces

**Comment by oly-baby** [comment]
> Please add the contents of this doc to https://github.com/open-telemetry/sig-security/blob/main/docs/recommendations.md

Good day @codeboten, I will be very grateful if explain more on what you mean by add the contents of this doc to......

**Comment by codeboten** [comment]
The recommendations in this PR overlap with this other PR https://github.com/open-telemetry/sig-security/pull/23/files @oly-baby @EjiroLaurelD

**Comment by oly-baby** [comment]
Good day @codeboten and @jpkrohling 

please i have added my work to the recommendation.md file.

check my pull request and please give me a feedback.

Thank you

**Review by jpkrohling — CHANGES_REQUESTED** [review]
I believe this is being under works by another participant already.

**Pull request closed without merging**
